# Generated by Django 4.0.1 on 2022-02-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kitab',
            fields=[
                ('kitab_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('kitab_name', models.CharField(max_length=200)),
                ('kitab_fromthePublisher', models.CharField(max_length=200)),
                ('kitab_abouttheAuthor', models.CharField(max_length=200)),
                ('Kitab_product_Details', models.CharField(max_length=800)),
                ('Kitab_image', models.FileField(upload_to='Kitab_image')),
            ],
            options={
                'db_table': 'Kitab',
            },
        ),
    ]
