# Generated by Django 4.0.1 on 2022-02-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kitab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Mbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitab.kitab')),
            ],
            options={
                'db_table': 'boking_musicalInstruments',
            },
        ),
    ]
